### ISSUE TITLE
If emacs reports a version number with three digits, packages are not included in the load path

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#13] opened 2016-10-07 18:31 UTC
Due to a change in how the constant 'doom-packages-dir' is initialized, emacs versions with more than three numbers will not be able to load packages downloaded by cask.

The current version of emacs in Arch, for instance, is 25.1.1. In it's current state, cask packages fail to load.

**Comment by hlissner** [comment] 2016-10-07 20:06
I recall [addressing this issue recently](https://github.com/hlissner/.emacs.d/commit/906c6e205540a0868436a0ac5dc06789449c9453). 

Here's the problem: in a recent update, Cask changed where it downloads plugins to:

It installs "bootstrap" packages to `.cask/25.1.1/bootstrap`, and installs the actual packages to `.cask/25.1/elpa`. I don't know why they made this change. It used to be all in the same folder (`.cask/25.1.1/{elpa,bootstrap}/*`). `doom-packages-dir` correctly accounts for this, but it won't move over your plugins.

So here are two solutions:

1. Move the old packages to the new place:

  ```bash
  mkdir ~/.emacs.d/.cask/25.1
  mv ~/.emacs.d/.cask/25.1.1/elpa ~/.emacs.d/.cask/25.1/elpa
  ```

2. Or reinstall your plugins with `make install`

Sorry about the sudden change! I don't even know if this is a bug on their end or intended behavior!

**Comment by hlissner** [comment] 2016-10-07 20:15
Ah, I found the [relevant commit in Cask](https://github.com/cask/cask/commit/c85700d8fb3522cb3f26bc0c668c90dd451ecd5c)

**Comment by hlissner** [comment] 2016-11-04 02:32
I'll close this for now. I hope the above solution helped! Let me know if it didn't.

**Closed by hlissner** 2016-11-04 02:32 UTC
