### ISSUE TITLE
make: *** [install] Error 255

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#41] opened 2017-03-22 22:43 UTC
Cannot open load file: No such file or directory, shackle

This is from a clean install, with the `.local` directory deleted.

**Comment by hlissner** [comment] 2017-03-22 23:57
Whoops. An oversight on my part. Should be fixed now.

**Comment by hlissner** [comment] 2017-03-28 20:08
I'll assume this has been fixed, since I can't reproduce it anymore. Feel free to reopen if that isn't the case.

**Closed by hlissner** 2017-03-28 20:08 UTC
