### ISSUE TITLE
make install fail on ubuntu arm

### ISSUE THREAD

**Issue by teliot** [hlissner/.emacs.d#67] opened 2017-05-19 05:30 UTC
$ DEBUG=1 make install
Eager macro-expansion failure: (void-function cl-remove-if)
Symbol's function definition is void: cl-remove-if
Makefile:59: recipe for target '.local/autoloads.el' failed
make: *** [.local/autoloads.el] Error 255

$ ls .local/
@odroidc1.home.local  packages

$ uname -a
Linux odroidc1 3.10.104-184 #1 SMP PREEMPT Mon Feb 20 06:38:17 UTC 2017 armv7l armv7l armv7l GNU/Linux

$ emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

d$ make -d install
GNU Make 4.1
Built for arm-unknown-linux-gnueabihf
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Updating makefiles....
 Considering target file 'Makefile'.
  Looking for an implicit rule for 'Makefile'.
  Trying pattern rule with stem 'Makefile'.
  Trying implicit prerequisite 'Makefile.o'.
  Trying pattern rule with stem 'Makefile'.

...... PRUNE .......

Considering target file 'install'.
 File 'install' does not exist.
  Considering target file 'init.el'.
   Finished prerequisites of target file 'init.el'.
  No need to remake target 'init.el'.
  Considering target file '.local/autoloads.el'.
   File '.local/autoloads.el' does not exist.
   Finished prerequisites of target file '.local/autoloads.el'.
  Must remake target '.local/autoloads.el'.
Putting child 0x5cf18 (.local/autoloads.el) PID 13182 on the chain.
Live child 0x5cf18 (.local/autoloads.el) PID 13182
Eager macro-expansion failure: (void-function cl-remove-if)
Symbol's function definition is void: cl-remove-if
Reaping losing child 0x5cf18 PID 13182
Makefile:59: recipe for target '.local/autoloads.el' failed
make: *** [.local/autoloads.el] Error 255
Removing child 0x5cf18 PID 13182 from chain.

**Comment by cosminilie** [comment] 2017-05-19 08:24
Same problem on OSX:

~/.emacs.d (master) DEBUG=1 make install
Symbol's function definition is void: advice-add
make: *** [.local/autoloads.el] Error 255

~/.emacs.d (master) uname -a
Darwin xxxx 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin

Emacs Version 25.2 (9.0)

**Comment by hlissner** [comment] 2017-05-19 08:47
I've pushed a fix specifically for the missing cl-remove-if. 

However, on Ubuntu I see you're using Emacs 24.4. This config _will_ break on versions under 25.1. Not that this specific error was caused by this, but this won't be the last error you get!

**Comment by cosminilie** [comment] 2017-05-19 08:53
The issue for me, was that the default emacs in CLI was the old one from OSX. Added an alias to use the brew one and now it works.

**Comment by hlissner** [comment] 2017-05-19 08:54
Excellent! And thank you!

**Closed by hlissner** 2017-05-19 08:54 UTC
