### ISSUE TITLE
`Symbol's function definition is void: package-installed-p` on startup when byte-compiled

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#33] opened 2017-03-02 00:45 UTC

**Comment by hlissner** [comment] 2017-03-02 04:48
I think this was caused by [#5b9a32](https://github.com/hlissner/.emacs.d/commit/5b9a32e2153d3f6aeca01db07095481b30603b2b) and fixed in [#ca36281](https://github.com/hlissner/.emacs.d/commit/ca362818afba9f7e46bbcdea8ada57b630acc263). I was experimenting with lexical-binding, and it snuck into that commit. If you could, please update and see if the issue is still around.

**Comment by hlissner** [comment] 2017-03-02 05:03
Another possibility: once byte compiled, package.el is not initialized, so none of the package-* functions will be available. If any part of a module (with `def-package!` calls) fails to compile during compilation, then you'll get this error.

So, I've added a check to `def-package!` just in case that ever happens.

**Comment by rjww** [comment] 2017-03-02 05:33
Whatever it was, it looks like it's fine after the most recent commit. Thanks!

**Comment by rjww** [comment] 2017-03-02 05:45
Wait, sorry, now the modeline isn't showing up.

**Comment by hlissner** [comment] 2017-03-02 05:58
Try reloading the autoloads: `make autoloads` or `doom/reload-autoloads`. I've changed some of the autoloaded functions doom-modeline depends on within the last 20 minutes.

**Comment by rjww** [comment] 2017-03-02 06:22
Yep, I'm an idiot. Thanks again!

**Comment by hlissner** [comment] 2017-03-02 06:26
No problem! Sorry for all the breaking updates.

**Closed by hlissner** 2017-03-02 06:26 UTC
